### ISSUE TITLE
Disable the kick message

### ISSUE THREAD

**Issue by vitkarpov** [wachter-org/wachter-bot#8]
Привет!

Во-первых, спасибо за такого прекрасного бота 👍 🥇 

<img width="560" alt="Screenshot 2023-01-02 at 11 51 36" src="https://user-images.githubusercontent.com/3001791/210227850-ef7cb966-86bb-40db-b4c2-2fabc87cd0cf.png">

^ недавно случился вот такой разговор. И я понял, что отключить сообщение об удалении пользователя из чата нельзя. Решил завести ишью, чтобы обсудить имеет ли смысл добавить такую возможность.

P.S. Готов сделать пулл-реквест.

**Comment by FTi130** [comment]
сделали в итоге?

**Comment by vitkarpov** [comment]
Сделал пулл-реквест https://github.com/nkonin/wachter_bot/pull/9
@nkonin please review

**Comment by nkonin** [comment]
@vitkarpov выложу вечером, когда вспомню как релизить вахтера
